config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    resources :products
  end
  get "*path", to: "react#show", constraints: ->(request) do
    !request.xhr? && request.format.html?
  end
  # Defines the root path route ("/")
  root "react#show"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", :as => :rails_health_check
  post "/checkout", to: "checkout#create"

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", :as => :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", :as => :pwa_manifest
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :promotion, optional: true
  validates :price, presence: true, numericality: {greater_than: 0}
end

app/models/promotion.rb
class Promotion < ApplicationRecord
  has_many :post
  validates :discount,
    numericality: {
      greater_than_or_equal_to: 0,
      less_than_or_equal_to: 1,
      allow_nil: true
    }
end

app/controllers/admin/products_controller.rb
module Admin
  class ProductsController < ApplicationController
    def index
      @products = Product.all

      respond_to do |format|
        format.html
        format.json { render json: @products }
      end
    end

    def show
      @product = Product.find(params[:id])

      respond_to do |format|
        format.html
        format.json { render json: @product.as_json(include: [:promotion]) }
      end
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/checkout_controller.rb
class CheckoutController < ApplicationController
  def create
    result = CheckoutCalculator.new(cart: checkout_params).call
    render json: result, status: :ok
  end

  private

  def checkout_params
    params.require(:checkout).permit(:total_cost, items: [:price, :name, :code, :quantity, :cost])
  end
end

app/controllers/react_controller.rb
class ReactController < ApplicationController
  def show
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/products/index.html.erb
<h1>List of all products</h1>
<% @products.each do |product| %>
    <p>
    <%= link_to product.name, admin_product_path(product.id) %>
    </p>
<% end %>

app/views/admin/products/show.html.erb
<%= link_to "Back to products", root_path %>
<h1><%= "Administrative page for #{@product.name}" %> <h1>
<span><%= @product.description %></span>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Amenitiz" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%= vite_client_tag %>
    <%= vite_javascript_tag "index.jsx" %>

  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/products/index.html.erb
<h1>List of all products</h1>
<% @products.each do |product| %>
    <p>
    <%= link_to product.name, product_path(product.id) %>
    </p>
<% end %>

app/views/react/show.html.erb
<div id="app"/>